const fakeCards = [
    {
        id: 4577193220898816,
        parentId: 5067401930473472,
        status: 1,
        paragraphId: -1,
        source: "https://uniontestprep.com/teas/practice-test/science/pages/52",
        question: "A large amount of energy is produced in the center of sun by which phenomenon?",
        hint: "",
        explanation: "Nuclear fusion is a nuclear process where mass is converted to energy. It occurs in the sun and stars.",
        choices: ["radioactive decay", "chemical reaction", "nuclear fission"],
        answers: ["nuclear fusion"],
        image: "",
        audio: "",
        video: "",
        point: 0,
        hasChild: 0,
        shortId: 10307,
        createDate: 1568179689244,
        lastUpdate: 1556941738809,
        rootTopicId: 5186025303310336,
        topicId: -1,
        index: 0,
    },
    {
        id: 4619645214523392,
        parentId: 5067401930473472,
        status: 1,
        paragraphId: -1,
        source: "https://uniontestprep.com/teas/practice-test/science/pages/43",
        question: "The law of conservation of mass states that <code>____</code>.",
        hint: "",
        explanation: "The mass remains conserved during a chemical reaction i.e., total mass remains constant before and after the reaction.",
        choices: ["The total mass of all products of a chemical react… mass of all the reactants. They are not related.", "The total mass of all products of a chemical react…is more than the total mass of all the reactants.", "The total mass of all products of a chemical react…ause some mass coverts to energy during reaction."],
        answers: ["The total mass of all products of a chemical react… is equal to the total mass of all the reactants."],
        image: "",
        audio: "",
        video: "",
        point: 0,
        hasChild: 0,
        shortId: 10308,
        createDate: 1568179689244,
        lastUpdate: 1556941738809,
        rootTopicId: 5186025303310336,
        topicId: -1,
        index: 0,
    },
    {
        id: 4641592900059136,
        parentId: 5067401930473472,
        status: 1,
        paragraphId: -1,
        source: "https://uniontestprep.com/teas/practice-test/science/pages/33",
        question: "During inhalation, what changes occur in the diaphragm?",
        hint: "",
        explanation: "The diaphragm moves downward during the inhalation of air due to the thoracic volume increasing and pressure decreasing. Air moves in due to low thoracic pressure in lungs and the lungs expand. <br> For more information about this, consult this source: https://www.nhlbi.nih.gov/health/health-topics/topics/hlw/whathappens.",
        choices: ["The diaphragm muscles relax, making it dome-shaped.", "The abdominal muscles contract, making the diaphragm move upward.", "The diaphragm muscles contract or tighten and move upward."],
        answers: ["The diaphragm muscles contract or tighten and the diaphragm moves downward."],
        image: "",
        audio: "",
        video: "",
        point: 0,
        hasChild: 0,
        shortId: 10309,
        createDate: 1568179689244,
        lastUpdate: 1556941738809,
        rootTopicId: 5186025303310336,
        topicId: -1,
        index: 0,
    }
];
export { fakeCards };
